services:
  api: 
    image: rg.fr-par.scw.cloud/atut-group-1/g1-simface-backend
    ports: 
      - "5000:5000"
    volumes: 
      - ./backend:/backend
    container_name: api
    networks:
      - app_network
    restart: always

  app:
    image: rg.fr-par.scw.cloud/atut-group-1/g1-simface-frontend
    ports:
      - "5001:80"
    volumes:
      - ./frontend:/frontend
    container_name: frontend
    networks:
      - app_network
    restart: always

networks:
  app_network:
    driver: bridge

